services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y libzbar0
      pip install -r requirements.txt
    startCommand: "gunicorn app:app"
